### ISSUE TITLE
TomTom and Here Not Connecting

### ISSUE THREAD

**Issue by christianl1979** [plusCubed/velociraptor#114]
Since some weeks TomTom and Here could not connect. 
TomTom
From Cache: False
Error: 401 Authentication token is not valid

So i only can use the OSM Information, but in my region only a few speed limits online.

**Comment by redline440** [comment]
Same issue for me. Was working perfectly until I uninstalled the Velociraptor app temporarily while trying to correct an issue with Bluetooth in a different application. Has never worked with the Here maps since then. I too get the same "Error: 401 Authentication token is not valid"

**Comment by plusCubed** [comment]
Hi all, sorry for the late response, it looks like a problem with the backend provider. It should be fixed within the next few days. Feel free to email me your subscription order numbers, I can refund this period.

**Comment by christianl1979** [comment]
Maybe if this problem wit the backend provider is fixed you can update the app so we can disable osm? OSM in Germany not really works i think, but tomtom works really good. 

Today (29.06.2020) the problem with the backend provider is still the same.

**Comment by plusCubed** [comment]
Hi! This should be fixed now. 

@christianl1979 The app already automatically prioritizes HERE > TomTom > OSM, so if it is querying OSM, that means HERE/TomTom didn't have it either.
