### ISSUE TITLE
Opacity to sign(s)

### ISSUE THREAD

**Issue by uicnren** [plusCubed/velociraptor#12]
Perhaps an option to allow for different levels of opacity for the on screen sign(s).

And/or for the speed limit sign, an option to make it a darker(adjustable opacity) background, with white lettering.

**Comment by plusCubed** [comment]
For the second request - #2

**Comment by D000DM000R** [comment]
I think it would be great if we could adjust the transparency so we can see the map behind the speed and speed limit sign.

**Comment by techguyone** [comment]
Transparency would be good, at least of the circle & border

**Comment by 1454** [comment]
As for kind of add on to this, I would like to see, or rather see the speed limit sign turn red at my predefined overage limit. I'd be willing to pay via another iap for this feature. Thanks again for implementing my other feature (and/or for mph or %)

**Comment by plusCubed** [comment]
Added a few updates ago.
