### ISSUE TITLE
Show when driving is detected

### ISSUE THREAD

**Issue by droopanu** [plusCubed/velociraptor#13]
Would it be possible to add an option to show the speed only when driving is detected and maps is open?
I believe you could use the activity recognition for that :)

Cheers,
Liviu

**Comment by charismacharisma** [comment]
I'd also like to have this, I use Tasker to recognise movement so a plugin or an intent to show / hide widgets would be great

**Comment by plusCubed** [comment]
@charismacharisma #24

**Comment by plusCubed** [comment]
Merged into #29
