### ISSUE TITLE
Speeding warning as read number but not %

### ISSUE THREAD

**Issue by BunnyQ** [plusCubed/velociraptor#14]
Eg. 5mph not 5%.

**Comment by hoevenpe** [comment]
That would be great, in our country the speeding tickets arrive at a fixed number of exceeded km's. 
So a selector allowing any number between 0 and 50 would be great. 

Please also add the option 'none' to use the application without any speed limit warning at all.

**Comment by plusCubed** [comment]
Done in 1.2.0
