### ISSUE TITLE
Get it to work with Android Auto

### ISSUE THREAD

**Issue by adefaria** [plusCubed/velociraptor#20]
I had recently gotten Android Auto in my car. One thing that AA lacks is a speed limit thing. I was hoping that this would work with Android Auto overlying the speed limit on the big screen in my car but it doesn't work. It'd be really cool if you could get that to work. Hell Google may buy you!

**Comment by plusCubed** [comment]
Unfortunately that is not possible with Auto's APIs right now - they only allow music and messaging apps, and I don't expect them to add floating windows to that list anytime soon. Sound alerts (#6) will be added soon though, and that'll work regardless of Auto.

**Comment by StSt1408** [comment]
Could we re open this Topic if it could work now in 2022? @plusCubed
