### ISSUE TITLE
App is always asking for GPS even when not in use

### ISSUE THREAD

**Issue by mmogithub** [plusCubed/velociraptor#21]
With 18/04/2016 update (1.1.5) Velociraptor is always asking for GPS even when not in use.
For example I'm at work, with no GPS 'cause i do not need it but Velociraptor is notifiying me almost once a minute.

This is very anoying so I've revoked notify permission with CyanogenMod ApsOps.

Here is some screenshots and a logcat.
https://goo.gl/photos/95TsLoStmZEPUERHA
https://goo.gl/photos/JxAzQ4gXJpPGBD4j6

04-20 15:44:01.004: D/Index(10922): Locale 'es_ES' is already indexed
04-20 15:44:01.014: D/OpenGLRenderer(10922): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-20 15:44:01.139: D/WifiService(844): New client listening to asynchronous messages
04-20 15:44:01.151: D/BluetoothManagerService(844): Message: 20
04-20 15:44:01.151: D/BluetoothManagerService(844): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@bc0b17d:true
04-20 15:44:01.158: D/BluetoothManagerService(844): Message: 30
04-20 15:44:01.161: D/BluetoothManagerService(844): Message: 30
04-20 15:44:01.163: D/LocalBluetoothProfileManager(10922): Adding local MAP profile
04-20 15:44:01.165: D/BluetoothMap(10922): Create BluetoothMap proxy object
04-20 15:44:01.166: D/BluetoothManagerService(844): Message: 30
04-20 15:44:01.167: D/BluetoothManagerService(844): Message: 30
04-20 15:44:01.168: D/LocalBluetoothProfileManager(10922): LocalBluetoothProfileManager construction complete
04-20 15:44:01.176: D/PhoneInterfaceManager(1616): [PhoneIntfMgr] getDataEnabled: subId=1 phoneId=0
04-20 15:44:01.177: D/PhoneInterfaceManager(1616): [PhoneIntfMgr] getDataEnabled: subId=1 retVal=false
04-20 15:44:01.177: D/TelephonyManager(10922): getDataEnabled: retVal=false
04-20 15:44:01.325: D/DashboardSummary(10922): rebuildUI took: 295 ms
04-20 15:44:01.379: I/Adreno-EGL(10922): <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I389a668de0)
04-20 15:44:01.379: I/Adreno-EGL(10922): OpenGL ES Shader Compiler Version: E031.28.00.04
04-20 15:44:01.379: I/Adreno-EGL(10922): Build Date: 10/24/15 Sat
04-20 15:44:01.379: I/Adreno-EGL(10922): Local Branch: mybranch15621148
04-20 15:44:01.379: I/Adreno-EGL(10922): Remote Branch: quic/LA.BF.1.1.3_rb1.3
04-20 15:44:01.379: I/Adreno-EGL(10922): Local Patches: NONE
04-20 15:44:01.379: I/Adreno-EGL(10922): Reconstruct Branch: NOTHING
04-20 15:44:01.382: I/OpenGLRenderer(10922): Initialized EGL, version 1.4
04-20 15:44:01.442: D/Index(10922): Deleting data for locale 'es_ES' took 26 millis
04-20 15:44:01.464: D/Index(10922): Indexing locale 'es_ES' took 21 millis
04-20 15:44:01.502: D/Index(10922): Deleting data for locale 'es_ES' took 3 millis
04-20 15:44:01.503: D/Index(10922): Indexing locale 'es_ES' took 1 millis
04-20 15:44:01.746: I/ActivityManager(844): Displayed com.android.settings/.Settings: +1s111ms
04-20 15:44:01.749: D/Index(10922): Deleting data for locale 'es_ES' took 5 millis
04-20 15:44:01.770: D/Index(10922): Indexing locale 'es_ES' took 21 millis
04-20 15:44:05.256: I/ActivityManager(844): START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from uid 1000 on display 0
04-20 15:44:05.339: D/SubSettings(10922): Launching fragment com.android.settings.cyanogenmod.PrivacySettings
04-20 15:44:05.462: I/ActivityManager(844): Displayed com.android.settings/.SubSettings: +186ms
04-20 15:44:05.490: D/OpenGLRenderer(10922): endAllStagingAnimators on 0x9b525a80 (RippleDrawable) with handle 0x9a9c4410
04-20 15:44:06.945: I/ActivityManager(844): START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from uid 1000 on display 0
04-20 15:44:07.005: D/SubSettings(10922): Launching fragment com.android.settings.privacyguard.PrivacyGuardManager
04-20 15:44:07.226: I/ActivityManager(844): Displayed com.android.settings/.SubSettings: +265ms
04-20 15:44:07.292: D/OpenGLRenderer(10922): endAllStagingAnimators on 0x9aa6b780 (ListView) with handle 0x9a9c4530
04-20 15:44:07.536: D/NetlinkSocketObserver(844): NeighborEvent{elapsedMs=958530, 10.1.32.1, [00000C07AC1D], RTM_NEWNEIGH, NUD_PROBE}
04-20 15:44:15.225: I/ThermalEngine(270): TM Id 'SKIN_THERMAL_management_1' Sensor 'xo_therm_pu2' - alarm raised 2 at 42.0 degC
04-20 15:44:15.225: I/ThermalEngine(270): ACTION: CPU - Setting CPU[0] to 1574400
04-20 15:44:15.225: I/ThermalEngine(270): ACTION: CPU - Setting CPU[1] to 1574400
04-20 15:44:15.225: I/ThermalEngine(270): ACTION: CPU - Setting CPU[2] to 1574400
04-20 15:44:15.225: I/ThermalEngine(270): ACTION: CPU - Setting CPU[3] to 1574400
04-20 15:44:15.226: I/ThermalEngine(270): ACTION: LCD - Setting max LCD brightness to 204
04-20 15:44:16.197: I/ActivityManager(844): START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from uid 1000 on display 0
04-20 15:44:16.282: D/SubSettings(10922): Launching fragment com.android.settings.applications.AppOpsDetails
04-20 15:44:16.505: I/ActivityManager(844): Displayed com.android.settings/.SubSettings: +293ms
04-20 15:44:16.565: D/OpenGLRenderer(10922): endAllStagingAnimators on 0xaef45b80 (ListView) with handle 0x9a9c4970
04-20 15:44:18.663: I/ActivityManager(844): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.cyanogenmod.trebuchet/com.android.launcher3.Launcher (has extras)} from uid 1000 on display 0
04-20 15:44:18.737: D/skia(1634): --- SkImageDecoder::Factory returned null
04-20 15:44:18.739: W/ImageView(1634): Unable to find resource: 2130837919
04-20 15:44:18.739: W/ImageView(1634): android.content.res.Resources$NotFoundException: File res/drawable/ic_mic_widget.xml from drawable resource ID #0x7f02019f
04-20 15:44:18.739: W/ImageView(1634):     at android.content.res.Resources.loadDrawableForCookie(Resources.java:2733)
04-20 15:44:18.739: W/ImageView(1634):     at android.content.res.Resources.loadDrawable(Resources.java:2633)
04-20 15:44:18.739: W/ImageView(1634):     at android.content.res.Resources.getDrawable(Resources.java:843)
04-20 15:44:18.739: W/ImageView(1634):     at android.content.res.Resources.getDrawable(Resources.java:818)
04-20 15:44:18.739: W/ImageView(1634):     at android.content.Context.getDrawable(Context.java:458)
04-20 15:44:18.739: W/ImageView(1634):     at android.widget.ImageView.resolveUri(ImageView.java:813)
04-20 15:44:18.739: W/ImageView(1634):     at android.widget.ImageView.setImageResource(ImageView.java:420)
04-20 15:44:18.739: W/ImageView(1634):     at java.lang.reflect.Method.invoke(Native Method)
04-20 15:44:18.739: W/ImageView(1634):     at android.widget.RemoteViews$ReflectionAction.apply(RemoteViews.java:1311)
04-20 15:44:18.739: W/ImageView(1634):     at android.widget.RemoteViews.performApply(RemoteViews.java:2845)
04-20 15:44:18.739: W/ImageView(1634):     at android.widget.RemoteViews.apply(RemoteViews.java:2787)
04-20 15:44:18.739: W/ImageView(1634):     at android.widget.RemoteViews.apply(RemoteViews.java:2747)
04-20 15:44:18.739: W/ImageView(1634):     at android.appwidget.AppWidgetHostView.updateAppWidget(AppWidgetHostView.java:393)
04-20 15:44:18.739: W/ImageView(1634):     at com.android.launcher3.LauncherAppWidgetHostView.updateAppWidget(LauncherAppWidgetHostView.java:69)
04-20 15:44:18.739: W/ImageView(1634):     at android.appwidget.AppWidgetHost.updateAppWidgetView(AppWidgetHost.java:403)
04-20 15:44:18.739: W/ImageView(1634):     at android.appwidget.AppWidgetHost.startListening(AppWidgetHost.java:194)
04-20 15:44:18.739: W/ImageView(1634):     at com.android.launcher3.LauncherAppWidgetHost.startListening(LauncherAppWidgetHost.java:71)
04-20 15:44:18.739: W/ImageView(1634):     at com.android.launcher3.Launcher.onAppWidgetHostReset(Launcher.java:2849)
04-20 15:44:18.739: W/ImageView(1634):     at com.android.launcher3.Launcher.onStart(Launcher.java:1102)
04-20 15:44:18.739: W/ImageView(1634):     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
04-20 15:44:18.739: W/ImageView(1634):     at android.app.Activity.performStart(Activity.java:6268)
04-20 15:44:18.739: W/ImageView(1634):     at android.app.Activity.performRestart(Activity.java:6314)
04-20 15:44:18.739: W/ImageView(1634):     at android.app.Activity.performResume(Activity.java:6319)
04-20 15:44:18.739: W/ImageView(1634):     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
04-20 15:44:18.739: W/ImageView(1634):     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
04-20 15:44:18.739: W/ImageView(1634):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
04-20 15:44:18.739: W/ImageView(1634):     at android.os.Handler.dispatchMessage(Handler.java:102)
04-20 15:44:18.739: W/ImageView(1634):     at android.os.Looper.loop(Looper.java:148)
04-20 15:44:18.739: W/ImageView(1634):     at android.app.ActivityThread.main(ActivityThread.java:5461)
04-20 15:44:18.739: W/ImageView(1634):     at java.lang.reflect.Method.invoke(Native Method)
04-20 15:44:18.739: W/ImageView(1634):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-20 15:44:18.739: W/ImageView(1634):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-20 15:44:18.739: W/ImageView(1634): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: <bitmap> requires a valid 'src' attribute
04-20 15:44:18.739: W/ImageView(1634):     at android.graphics.drawable.BitmapDrawable.updateStateFromTypedArray(BitmapDrawable.java:764)
04-20 15:44:18.739: W/ImageView(1634):     at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:724)
04-20 15:44:18.739: W/ImageView(1634):     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
04-20 15:44:18.739: W/ImageView(1634):     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124)
04-20 15:44:18.739: W/ImageView(1634):     at android.content.res.Resources.loadDrawableForCookie(Resources.java:2723)
04-20 15:44:18.739: W/ImageView(1634):     ... 31 more
04-20 15:44:18.823: I/art(844): Background partial concurrent mark sweep GC freed 83652(6MB) AllocSpace objects, 5(100KB) LOS objects, 32% free, 32MB/48MB, paused 1.606ms total 117.805ms
04-20 15:44:19.352: W/OpenGLRenderer(1634): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
04-20 15:44:19.352: W/OpenGLRenderer(1634): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
04-20 15:44:22.419: I/ActivityManager(844): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.pluscubed.velociraptor/.SettingsActivity (has extras)} from uid 10021 on display 0
04-20 15:44:22.433: W/BroadcastQueue(844): Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=1634, uid=10021) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver
04-20 15:44:22.433: W/BroadcastQueue(844): Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=1634, uid=10021) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.googlequicksearchbox/com.google.android.apps.gsa.search.core.icingsync.ApplicationLaunchReceiver
04-20 15:44:24.133: W/AwContents(6817): onDetachedFromWindow called when already detached. Ignoring
04-20 15:44:24.280: W/BindingManager(6817): Cannot call determinedVisibility() - never saw a connection for the pid: 6817
04-20 15:44:26.571: I/OpenGLRenderer(844): Initialized EGL, version 1.4
04-20 15:44:26.709: D/PhoneStatusBar(1026): disable: < EXPAND* icons alerts system_info back home recent clock search quick_settings >
04-20 15:44:27.160: D/ConnectivityService(844): notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
04-20 15:44:27.852: W/InputMethodManagerService(844): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@3ad7780 attribute=null, token = android.os.BinderProxy@3eca65c
04-20 15:44:27.875: I/ActivityManager(844): Start proc 11121:com.android.systemui:screenshot/u0a18 for service com.android.systemui/.screenshot.TakeScreenshotService
04-20 15:44:27.875: D/PhoneStatusBar(1026): disable: < expand* icons alerts system_info back home recent clock search quick_settings >
04-20 15:44:27.954: W/System(11121): ClassLoader referenced unknown path: /system/priv-app/SystemUI/lib/arm
04-20 15:44:27.960: I/LoadedApk(11121): No resource references to update in package common
04-20 15:44:27.960: I/LoadedApk(11121): No resource references to update in package com.blissroms.moelle.ddoverhauled
04-20 15:44:27.960: I/LoadedApk(11121): No resource references to update in package com.blissroms.moelle.ddoverhauled
04-20 15:44:27.960: I/LoadedApk(11121): No resource references to update in package com.hd.plane
04-20 15:44:29.078: D/PermissionCache(250): checking android.permission.READ_FRAME_BUFFER for uid=10018 => granted (234 us)
04-20 15:44:29.135: D/OpenGLRenderer(11121): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-20 15:44:29.158: W/ServiceManager(257): Permission failure: com.oma.drm.permission.ACCESS_OMA_DRM from uid=10018 pid=11121
04-20 15:44:29.177: I/Adreno-EGL(11121): <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I389a668de0)
04-20 15:44:29.177: I/Adreno-EGL(11121): OpenGL ES Shader Compiler Version: E031.28.00.04
04-20 15:44:29.177: I/Adreno-EGL(11121): Build Date: 10/24/15 Sat
04-20 15:44:29.177: I/Adreno-EGL(11121): Local Branch: mybranch15621148
04-20 15:44:29.177: I/Adreno-EGL(11121): Remote Branch: quic/LA.BF.1.1.3_rb1.3
04-20 15:44:29.177: I/Adreno-EGL(11121): Local Patches: NONE
04-20 15:44:29.177: I/Adreno-EGL(11121): Reconstruct Branch: NOTHING
04-20 15:44:29.179: I/OpenGLRenderer(11121): Initialized EGL, version 1.4
04-20 15:44:29.188: W/SoundPool(11121):   sample 1 not READY
04-20 15:44:29.211: I/OMXClient(11121): Using client-side OMX mux.
04-20 15:44:30.184: D/ConnectivityService(844): notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
04-20 15:44:30.802: I/art(844): Background partial concurrent mark sweep GC freed 18913(1295KB) AllocSpace objects, 4(80KB) LOS objects, 32% free, 33MB/49MB, paused 1.334ms total 151.830ms
04-20 15:44:31.439: I/art(844): Background partial concurrent mark sweep GC freed 7143(519KB) AllocSpace objects, 0(0B) LOS objects, 32% free, 33MB/49MB, paused 1.457ms total 138.715ms
04-20 15:44:31.457: I/iu.UploadsManager(1694): NEW; upload media id: 31308; iu: 0
04-20 15:44:31.478: I/iu.UploadsManager(1694): End new media; added: 1, uploading: 1, time: 189 ms
04-20 15:44:31.528: I/iu.SyncManager(1694): --- NEW; upload; task: [aw; reason: InstantUpload, id: 4720, accountId: 0]
04-20 15:44:31.535: I/NetworkCapability(1694): Active network type: 1
04-20 15:44:31.535: I/iu.SyncTask(1694): -- isAccepted state -- isBackgroundSync: true getMasterSync: true doAutoSync: true isConnected: true backgroundDataAllowed: true isPlugged: true isSyncOnBattery: true isNetworkMetered: false isMobileNetwork: false isSyncOnWifiOnly false isRoaming false isSyncOnRoaming true isSyncOnGCM: false
04-20 15:44:31.536: I/NetworkCapability(1694): Active network type: 1
04-20 15:44:31.537: I/iu.SyncManager(1694): REQUEST sync for [aw; reason: InstantUpload, id: 4720, accountId: 0]
04-20 15:44:31.571: I/iu.SyncService(1694): ====> Manual or requested up sync account=0
04-20 15:44:31.573: W/ActivityManager(844): Unable to start service Intent { cmp=com.google.android.apps.plus/com.google.android.apps.photos.service.PhotosService } U=0: not found
04-20 15:44:31.573: E/PhotosClient(1694): Binding to service failed, connection state is 0
04-20 15:44:31.632: I/iu.UploadsManager(1694): End new media; added: 0, uploading: 0, time: 60 ms
04-20 15:44:31.671: I/iu.SyncManager(1694): --- NEW; upload; task: [aw; reason: InstantUpload, id: 4720, accountId: 0]
04-20 15:44:31.678: I/NetworkCapability(1694): Active network type: 1
04-20 15:44:31.678: I/iu.SyncTask(1694): -- isAccepted state -- isBackgroundSync: true getMasterSync: true doAutoSync: true isConnected: true backgroundDataAllowed: true isPlugged: true isSyncOnBattery: true isNetworkMetered: false isMobileNetwork: false isSyncOnWifiOnly false isRoaming false isSyncOnRoaming true isSyncOnGCM: false
04-20 15:44:31.682: I/NetworkCapability(1694): Active network type: 1
04-20 15:44:31.682: I/iu.SyncManager(1694): SYNC; start task: [aw; reason: InstantUpload, id: 4720, accountId: 0]
04-20 15:44:31.683: I/iu.SyncTask(1694): --- START syncing InstantUpload; account: 0
04-20 15:44:31.729: I/iu.SyncTask(1694): +++ START; upload started; 4720
04-20 15:44:31.843: V/GLSActivity(2268): AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
04-20 15:44:31.845: V/GLSActivity(2268): AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
04-20 15:44:32.346: I/HttpUrlRequestFactory(1694): Using network stack: HttpUrlConnection/39.0.2163.0@ff61f86d
04-20 15:44:32.867: I/iu.SyncTask(1694): +++ START InstantUpload, task: 4720
04-20 15:44:32.868: I/iu.UploadsManager(1694): #reloadSettings(); account: 0; IU: enabled; IS: disabled; IS account: -1; photoWiFi: false; videoWiFi: false; roam: true; battery: true; size: STANDARD; maxMobile: 157286400
04-20 15:44:32.984: I/iu.UploadsManager(1694): upload full size; task: media_id: 31308, album_id: instant, event_id: null, upload_account_id: 0, upload_url: null, bytes_total: -1,  {InstantUpload, queued/in progress, uploading} [0%], remaining: 0
04-20 15:44:33.398: I/MediaUploader(1694): --- UPLOAD task: 67472583
04-20 15:44:36.872: I/iu.IUProvider(1694): Update quota settings;
04-20 15:44:37.014: I/iu.SyncTask(1694): +++ DONE; upload finished; 4720
04-20 15:44:37.015: I/iu.SyncTask(1694): --- DONE syncing InstantUpload; account: 0
04-20 15:44:37.055: I/iu.SyncManager(1694): SYNC; complete; result: SyncResult: stats [ numInserts: 1 numEntries: 1]
04-20 15:44:37.068: I/iu.UploadsManager(1694): num queued entries: 0
04-20 15:44:37.073: I/iu.UploadsManager(1694): num updated entries: 0
04-20 15:44:37.080: I/iu.SyncManager(1694): NEXT; no task
04-20 15:44:37.080: I/iu.SyncService(1694): ====> Sync complete
04-20 15:44:37.094: I/iu.UploadsManager(1694): num queued entries: 0
04-20 15:44:37.099: I/iu.UploadsManager(1694): num updated entries: 0
04-20 15:44:37.105: I/iu.SyncManager(1694): NEXT; no task
04-20 15:44:42.272: D/ConnectivityService(844): notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
04-20 15:44:45.294: D/ConnectivityService(844): notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
04-20 15:44:48.640: D/WifiService(844): acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@62d60f8}
04-20 15:44:48.643: I/iu.UploadsManager(1694): End new media; added: 0, uploading: 0, time: 103 ms
04-20 15:44:48.645: D/wifi(844): Initialized common fields 10000, 16, 100, 10
04-20 15:44:48.645: D/wifi(844): bucket[0] = 2:3:10000:2
04-20 15:44:48.751: I/ContextCompilationHandl(5407): Compiling grammar for: es-ES, type=CONTACT_DIALING
04-20 15:44:48.779: I/ContextCompilationHandl(5407): No grammar compilation resources for COMPILER, aborting.
04-20 15:44:48.779: I/ContextCompilationHandl(5407): Compiling grammar for: es-ES, type=HANDS_FREE_COMMANDS
04-20 15:44:48.783: I/ContextCompilationHandl(5407): No grammar compilation resources for COMPILER, aborting.
04-20 15:44:49.246: D/WifiService(844): releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@62d60f8}
04-20 15:44:49.263: I/GCoreUlr(2268): Successfully inserted 1 locations
04-20 15:44:49.265: I/GCoreUlr(2268): Cancelling scheduled uploads
04-20 15:44:49.266: I/GCoreUlr(2268): Not calling LocationReporter, hasMoved: false, elapsed millis: 796762, request: Stationary(3600000)
04-20 15:44:49.266: I/GCoreUlr(2268): Scheduling next upload for 2803238ms from now
04-20 15:44:49.916: W/AwContents(6817): onDetachedFromWindow called when already detached. Ignoring
04-20 15:44:50.179: W/BindingManager(6817): Cannot call determinedVisibility() - never saw a connection for the pid: 6817
04-20 15:44:53.126: W/InputEventReceiver(6817): Attempted to finish an input event but the input event receiver has already been disposed.
04-20 15:44:53.126: W/ViewRootImpl(6817): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=510.0, y[0]=1842.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=1, eventTime=1004109, downTime=1004059, deviceId=4, source=0x1002 }
04-20 15:44:53.126: W/InputEventReceiver(6817): Attempted to finish an input event but the input event receiver has already been disposed.
04-20 15:44:56.219: I/ActivityManager(844): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.cyanogenmod.trebuchet/com.android.launcher3.Launcher (has extras)} from uid 1000 on display 0
04-20 15:44:56.269: D/skia(1634): --- SkImageDecoder::Factory returned null
04-20 15:44:56.271: W/ImageView(1634): Unable to find resource: 2130837919
04-20 15:44:56.271: W/ImageView(1634): android.content.res.Resources$NotFoundException: File res/drawable/ic_mic_widget.xml from drawable resource ID #0x7f02019f
04-20 15:44:56.271: W/ImageView(1634):     at android.content.res.Resources.loadDrawableForCookie(Resources.java:2733)
04-20 15:44:56.271: W/ImageView(1634):     at android.content.res.Resources.loadDrawable(Resources.java:2633)
04-20 15:44:56.271: W/ImageView(1634):     at android.content.res.Resources.getDrawable(Resources.java:843)
04-20 15:44:56.271: W/ImageView(1634):     at android.content.res.Resources.getDrawable(Resources.java:818)
04-20 15:44:56.271: W/ImageView(1634):     at android.content.Context.getDrawable(Context.java:458)
04-20 15:44:56.271: W/ImageView(1634):     at android.widget.ImageView.resolveUri(ImageView.java:813)
04-20 15:44:56.271: W/ImageView(1634):     at android.widget.ImageView.setImageResource(ImageView.java:420)
04-20 15:44:56.271: W/ImageView(1634):     at java.lang.reflect.Method.invoke(Native Method)
04-20 15:44:56.271: W/ImageView(1634):     at android.widget.RemoteViews$ReflectionAction.apply(RemoteViews.java:1311)
04-20 15:44:56.271: W/ImageView(1634):     at android.widget.RemoteViews.performApply(RemoteViews.java:2845)
04-20 15:44:56.271: W/ImageView(1634):     at android.widget.RemoteViews.apply(RemoteViews.java:2787)
04-20 15:44:56.271: W/ImageView(1634):     at android.widget.RemoteViews.apply(RemoteViews.java:2747)
04-20 15:44:56.271: W/ImageView(1634):     at android.appwidget.AppWidgetHostView.updateAppWidget(AppWidgetHostView.java:393)
04-20 15:44:56.271: W/ImageView(1634):     at com.android.launcher3.LauncherAppWidgetHostView.updateAppWidget(LauncherAppWidgetHostView.java:69)
04-20 15:44:56.271: W/ImageView(1634):     at android.appwidget.AppWidgetHost.updateAppWidgetView(AppWidgetHost.java:403)
04-20 15:44:56.271: W/ImageView(1634):     at android.appwidget.AppWidgetHost.startListening(AppWidgetHost.java:194)
04-20 15:44:56.271: W/ImageView(1634):     at com.android.launcher3.LauncherAppWidgetHost.startListening(LauncherAppWidgetHost.java:71)
04-20 15:44:56.271: W/ImageView(1634):     at com.android.launcher3.Launcher.onAppWidgetHostReset(Launcher.java:2849)
04-20 15:44:56.271: W/ImageView(1634):     at com.android.launcher3.Launcher.onStart(Launcher.java:1102)
04-20 15:44:56.271: W/ImageView(1634):     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
04-20 15:44:56.271: W/ImageView(1634):     at android.app.Activity.performStart(Activity.java:6268)
04-20 15:44:56.271: W/ImageView(1634):     at android.app.Activity.performRestart(Activity.java:6314)
04-20 15:44:56.271: W/ImageView(1634):     at android.app.Activity.performResume(Activity.java:6319)
04-20 15:44:56.271: W/ImageView(1634):     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
04-20 15:44:56.271: W/ImageView(1634):     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
04-20 15:44:56.271: W/ImageView(1634):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
04-20 15:44:56.271: W/ImageView(1634):     at android.os.Handler.dispatchMessage(Handler.java:102)
04-20 15:44:56.271: W/ImageView(1634):     at android.os.Looper.loop(Looper.java:148)
04-20 15:44:56.271: W/ImageView(1634):     at android.app.ActivityThread.main(ActivityThread.java:5461)
04-20 15:44:56.271: W/ImageView(1634):     at java.lang.reflect.Method.invoke(Native Method)
04-20 15:44:56.271: W/ImageView(1634):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-20 15:44:56.271: W/ImageView(1634):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-20 15:44:56.271: W/ImageView(1634): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: <bitmap> requires a valid 'src' attribute
04-20 15:44:56.271: W/ImageView(1634):     at android.graphics.drawable.BitmapDrawable.updateStateFromTypedArray(BitmapDrawable.java:764)
04-20 15:44:56.271: W/ImageView(1634):     at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:724)
04-20 15:44:56.271: W/ImageView(1634):     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
04-20 15:44:56.271: W/ImageView(1634):     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124)
04-20 15:44:56.271: W/ImageView(1634):     at android.content.res.Resources.loadDrawableForCookie(Resources.java:2723)
04-20 15:44:56.271: W/ImageView(1634):     ... 31 more
04-20 15:44:56.353: I/art(844): Background partial concurrent mark sweep GC freed 26153(1601KB) AllocSpace objects, 3(60KB) LOS objects, 32% free, 33MB/49MB, paused 1.645ms total 115.104ms
04-20 15:44:56.861: W/OpenGLRenderer(1634): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
04-20 15:44:56.861: W/OpenGLRenderer(1634): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
04-20 15:44:58.518: D/audio_hw_primary(258): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
04-20 15:44:58.528: D/audio_hw_primary(258): start_output_stream: enter: stream(0xb5fb6e80)usecase(1: low-latency-playback) devices(0x2)
04-20 15:44:58.529: D/audio_hw_primary(258): start_output_stream: enter: usecase(1: low-latency-playback) devices(0x2)
04-20 15:44:58.529: D/audio_hw_primary(258): select_devices: out_snd_device(2: speaker) in_snd_device(0: )
04-20 15:44:58.529: W/msm8974_platform(258): Codec backend bitwidth 16, samplerate 48000
04-20 15:44:58.529: D/hardware_info(258): hw_info_append_hw_type : device_name = speaker
04-20 15:44:58.529: I/msm8974_platform(258): platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)
04-20 15:44:58.534: D/audio_hw_primary(258): select_devices: done
04-20 15:45:00.214: I/art(844): Background partial concurrent mark sweep GC freed 7465(498KB) AllocSpace objects, 16(680KB) LOS objects, 32% free, 32MB/48MB, paused 1.362ms total 177.558ms
04-20 15:45:01.013: I/ActivityManager(844): Start proc 11413:com.android.deskclock/u0a38 for broadcast com.android.deskclock/com.android.alarmclock.DigitalAppWidgetProvider
04-20 15:45:01.082: W/System(11413): ClassLoader referenced unknown path: /system/app/DeskClock/lib/arm
04-20 15:45:01.102: I/LoadedApk(11413): No resource references to update in package common
04-20 15:45:01.102: I/LoadedApk(11413): No resource references to update in package com.blissroms.moelle.ddoverhauled
04-20 15:45:01.102: I/LoadedApk(11413): No resource references to update in package com.blissroms.moelle.ddoverhauled
04-20 15:45:01.102: I/LoadedApk(11413): No resource references to update in package com.hd.plane
04-20 15:45:01.118: I/ActivityManager(844): Killing 5161:com.google.android.music:main/u0a139 (adj 15): empty #17
04-20 15:45:02.058: D/audio_hw_primary(258): out_standby: enter: stream (0xb5fb6e80) usecase(1: low-latency-playback)
04-20 15:45:02.124: D/hardware_info(258): hw_info_append_hw_type : device_name = speaker
04-20 15:45:12.247: D/NetlinkSocketObserver(844): NeighborEvent{elapsedMs=1023240, 10.1.32.1, [00000C07AC1D], RTM_NEWNEIGH, NUD_STALE}

-- 
Saludos

Moisés Montero

**Comment by plusCubed** [comment]
Fixed in 1.1.6+

**Comment by mmogithub** [comment]
Yes. Perfectly.
Well done.
Thnaks for your effort sir!
