### ISSUE TITLE
No Speed Limits shown in Australia 

### ISSUE THREAD

**Issue by hrtrulz** [plusCubed/velociraptor#23]
In trying this app, it shows no speed limits around Brisbane Australia. The speed limits map links shows speed limits where I was driving but the app shows nothing.

**Comment by plusCubed** [comment]
Is it still not working in the latest version 1.1.9?

**Comment by hrtrulz** [comment]
I will check it on the weekend to see if it is working.

**Comment by hrtrulz** [comment]
I tested again on the weekend, I was working most of the time. My guess is the data is missing when it was not working.
