### ISSUE TITLE
No speed limits showing in Atlanta

### ISSUE THREAD

**Issue by chickman72** [plusCubed/velociraptor#26]
Hi

After the last few updates, the speed limit box is populated about 5% of the time.  It used to work relatively well when i first installed it.  I'm running a Nexus 6.

Speedometer seems to work great.

Chris

**Comment by plusCubed** [comment]
Can you check the coverage map? I switched from HERE Maps (which was costing me a lot of money) to OpenStreetMap in version 1.1.0.

**Comment by chickman72** [comment]
One of the subsequent updates fixed the problem for the most part.  I can still reference the speed limits on my 2013 Ford Explorer with the Microsoft Sync system with Navigation.  For the most part, speed limits are now showing in the velociraptor floater.  However if there are no speed limits in velociratpor, I can typically see them on my Ford Nav system.  It's curious that my 3 year old sd based navigation system would have speed limits that the OpenStreetMaps would not have.

Thank you!  This is a great product!
