### ISSUE TITLE
Exceed Speed limit warning sound too quiet and not configurable.

### ISSUE THREAD

**Issue by joshuaos** [plusCubed/velociraptor#39]
I cannot hear the speed limit warning sound when playing music through my phone.  It would be nice to be able to change the pitch and volume of the sound.

**Comment by joshuaos** [comment]
One suggestion for a better more easily heard beep... 

   public static void playBeep() {
        try {
            new CountDownTimer(700, 300) {
                public void onFinish() {


                }

                public void onTick(long millisUntilFinished) {
                    // millisUntilFinished    The amount of time until finished.
                    ToneGenerator toneGen1 = new ToneGenerator(AudioManager.STREAM_NOTIFICATION, 100);
                    toneGen1.startTone(ToneGenerator.TONE_CDMA_CALL_SIGNAL_ISDN_PING_RING, 100);
                }
            }.start();
        } catch (RuntimeException ignored) {
            //TODO: Investigate RuntimeException
        }
    }

**Comment by RickPJ** [comment]
Could the warning beep be directed to the notification sound channel so the sound goes via BT to the car speakers? That would make it much more audible.

Ability to configure the sound would help too.

**Comment by plusCubed** [comment]
Added the increased volume in the latest source - will be out in the next update. 

I'm not adding the configurable sound for now - the default notification sounds don't have enough "warning-ness".
