### ISSUE TITLE
PUBLIC_OVERPASS_APIS possibly incorrect

### ISSUE THREAD

**Issue by joshuaos** [plusCubed/velociraptor#40]
In SpeedLimitApi the string PUBLIC_OVERPASS_APIS lists "http://api.openstreetmap.fr/oapi/" as one of the open street map api's but according to this: http://wiki.openstreetmap.org/wiki/Overpass_API the proper url is "http://api.openstreetmap.fr/oapi/interpreter/"

**Comment by plusCubed** [comment]
That page is incorrect, interpreter is the final endpoint. The French instance works fine in the app.
