### ISSUE TITLE
Suppress notification display

### ISSUE THREAD

**Issue by RickPJ** [plusCubed/velociraptor#43]
It's very annoying to have the notification icon present all the time, even when not using a map.

If a notification is required to keep the app in memory could it at least be low-priority so it's just in the pull-down without an icon?

I also have an option in the settings related to notifications, but it doesn't appear to do anything. Is this a bug?

**Comment by plusCubed** [comment]
Hi Rick, is the notification the "show/hide" notification? If so, you can swipe that away.

**Comment by RickPJ** [comment]
Doh! thanks.
