### ISSUE TITLE
Google maps in Driving mode?

### ISSUE THREAD

**Issue by RickPJ** [plusCubed/velociraptor#44]
It would be nice to have an option to only display the overlay in Google maps when in Driving mode (the new version of "Navigating").

Is that even technically feasible?

**Comment by RickPJ** [comment]
Expanding on this idea, I've realised that maps automatically switches into Driving mode when the phone is in Car Mode.
It would therefore make sense if Velociraptor could be configured to only display the overlay in car mode.
Maybe two options: car mode when selected apps are running; or always displayed whenever in car mode.

Any chance?

BTW, I use a car-home app that switches into car mode, not a dedicated dock.

**Comment by plusCubed** [comment]
The Google Maps activation is feasible by detecting the Driving notification.  Car Mode is also possible. I've added both to issue #29
