### ISSUE TITLE
Velociraptor app violates Overpass API usage policy

### ISSUE THREAD

**Issue by mmd-osm** [plusCubed/velociraptor#46]
Hi there,

according to the [Overpass API usage policy](https://wiki.openstreetmap.org/wiki/Overpass_API), your app should at most create 10.000 requests per day. Log files indicate that you're currently sending more than 500'000 requests per day and create a huge amount of traffic/load on the server.

Please get in touch with [Roland](https://wiki.openstreetmap.org/wiki/Overpass_API#Developers_.2F_System_Administrators) as soon as possible to discuss this situation.

CC: @drolbr

**Comment by plusCubed** [comment]
I've contacted Roland and begun the beta release for fixing this. Thanks for bringing this to my attention, and I sincerely apologize.

**Comment by mmd-osm** [comment]
One day of Velociraptor usage - currently running at 300k requests per day.

![bildschirmfoto vom 2017-01-15 17-31-18](https://cloud.githubusercontent.com/assets/5842757/22403296/2556aa3e-e613-11e6-9e45-52af73b2c199.png)

**Comment by mmd-osm** [comment]
New release and the move to a dedicated server significantly reduced the number of requests. Closing here. Thanks!

**Comment by mmd-osm** [comment]
I need to re-open this issue. Velociraptor/1.7.2 clients send more than  >250'000 requests by per day right now, which massively exceeds the permitted usage policy again. Appreciate a speedy resolution of this issue. Thanks.

**Comment by pluscubed** [comment]
Apologies, seem like there's been a recent increase in usage. I've redirected most traffic away from the main Overpass servers. Let me know if that reduces the usage.

**Comment by mmd-osm** [comment]
Thanks again for the quick reply! It looks like traffic has dropped to about 25k requests per day, which is less than 10% of what it used to be a few days back. So i'm closing the issue again for the time being...
