### ISSUE TITLE
Remove stopSelf() at line 207 from SpeedLimitService.java

### ISSUE THREAD

**Issue by SUPERCILEX** [plusCubed/velociraptor#55]
Hi,
I don't have a data connection, but I would still like to be able to use the speedometer from Velociraptor. Instead of killing the entire service, I think you should either just leave things as they are since you already have the toast saying that the speed limit doesn't work offline, or just hide the sign like in #50.

**Comment by plusCubed** [comment]
Done for 1.4.1 hotfix.

**Comment by plusCubed** [comment]
I will properly add hiding/disabling the speed limit as issue #50.

**Comment by SUPERCILEX** [comment]
Awesome! Thanks!
