### ISSUE TITLE
Add sound alert warning

### ISSUE THREAD

**Issue by plusCubed** [plusCubed/velociraptor#6]

**Comment by mkuchin** [comment]
+1

**Comment by D000DM000R** [comment]
Great idea!

**Comment by Dtrieb** [comment]
+1

**Comment by techguyone** [comment]
I'd quite like a simple beep when the speed limit changes, just as a heads up to the user, it needn't be anything excessive just a subtle beep, switchable in settings of course.

**Comment by akrueger** [comment]
+1

**Comment by hoevenpe** [comment]
I would prefer some kind of warning color limit (example 5%) and a higher warning sound limit (example 10%), please start the sound warning after a few seconds of exceeding the limit to prevent incorrect sounds when the limit is incorrect for a very short period (crossing a road on the highway)

**Comment by plusCubed** [comment]
Added, coming in the next update. Activates after 2 seconds above speed limit tolerance.
