### ISSUE TITLE
Speed limit doesn't show

### ISSUE THREAD

**Issue by Plumarh** [plusCubed/velociraptor#61]
Hi,

I love your app and the last feature you add (speed only in navigation) but I have a problem since 1.5.0.

The versions 1.5.0 and 1.5.1 doesn't work on my phone (Galaxy S7 6.0.1) : The speed limit is always ( -- )

I reinstalled the 1.4.1 and everything works as before.

Best regards,
Plumarh.

**Comment by plusCubed** [comment]
HERE Maps database has been re-added in 1.5.4 - you'll have to register an account in the Velociraptor settings. It should help with the OpenStreetMap server (which has been overloaded for some time). If that doesn't help, feel free to re-open the issue.

**Comment by Plumarh** [comment]
Hi,

I created an HERE account and registred it in Velociraptor (I put my HERE password in the "APP HERE code" text field, is it correct ?) 
This fix worked during 1 week but the problem is here again. No limit displayed (Same thing for Velociraptor and Velociraptor AA).

Thank you for your help.

**Comment by plusCubed** [comment]
The app id and code should be filled in from the HERE app page (not the account/password for the account). If you already registered, click "View Account" in Velociraptor and sign in. Select your project. You may need to click the "Generate App ID and App Code" button.

**Comment by Plumarh** [comment]
It works !
Thanks you ! =)
