### ISSUE TITLE
A bug + transaltion

### ISSUE THREAD

**Issue by Raffaele74** [plusCubed/velociraptor#62]
Translation: I didn't understand what "Intelligent caching fast refresh of speed limits" means. It isn't a translation problem. It is to short for me.

Best translation: I put in picture and in .txt

Set nerds: a problem. You can view in picture.

Short links: they don't work

![velociraptor](https://cloud.githubusercontent.com/assets/24221053/24614251/fcb51c0a-188a-11e7-973a-8e96e3da81ae.png)
[Velociraptor.txt](https://github.com/plusCubed/velociraptor/files/890370/Velociraptor.txt)

**Comment by plusCubed** [comment]
1. The debugging window doesn't capture touch, you can touch through it.
2. "Intelligent caching" isn't too important, it just means the speed limits are kept around locally to avoid having to go to the network. I am currently not including translations of the store listing, but I'll see if I can add that to OneSky. I've created #66.
3. All of the goo.gl links work for me. Your Chrome says there is a tunnel error - it's unrelated.
