### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Raffaele74** [plusCubed/velociraptor#63]
Some comment about setting.

![comments](https://cloud.githubusercontent.com/assets/24221053/24616795/6759e386-1892-11e7-8596-67ca68895e6e.png)

**Comment by plusCubed** [comment]
The accessibility permission should allow multiple apps - what phone and Android version are you running? Can you provide a screenshot of the accessibility settings?

Android Auto integration is available only in the Velociraptor AA version. (Android Auto is a head unit system in certain newer cars). There should be a little popup at the bottom saying that.

Show notification controls should create a notification with "show" and "hide" options to manually toggle Velociraptor.

**Comment by Raffaele74** [comment]
Accessibility. I was wrong. I'm Android 6 Huawei. It is not "permanent". I did'n understand why, but often Android set it off automatic.
Anyway, Velociraptor remembers that I setted on and, so, I cannot easy  setting on (the others time) this permission. I must do by ANdroid setting.

You are right. But I dislike (I must push, I must read pop up, pup up is faster ....). Why not as comment? View picture.

Show notification doesn't show anything.

![6759e386-1892-11e7-8596-67ca68895e6e](https://cloud.githubusercontent.com/assets/24221053/24652781/685d0992-1933-11e7-9977-8c93a0793640.png)

**Comment by Raffaele74** [comment]
Accessibility. Solved in translation.
Others remained.

**Comment by plusCubed** [comment]
"Show notifications controls" does not work on some older devices due to vector file problems. The top setting only depends on what Android tells the app - if the OS reports it incorrectly there's not much I can do. On Huawei devices, you may need to go to Settings > Apps > Advanced Options > Ignore Optimations  and enable Velociraptor.

**Comment by Raffaele74** [comment]
??? 
I didn't understand. I try to understand.

What "Notifications control" seems? Android notifications? App notifications?
Notification are txt or vectorial?
Why "Ignore Optimations"? Notifications page is "Notifications panel and status bars"

On my device app doesn't show nothing when I push (neither a check symbol).

I'm not older device, I know "Ignore Optimations" so I did long time ago.

**Comment by plusCubed** [comment]
1.6.0 has a re-organized screen that hopefully makes things clearer. Let me know if it makes more sense!

**Comment by Raffaele74** [comment]
Hi.
Fitst annex: I cannot know if you can, but text "it's ok" when buttom is disable text should be clear.
Other annexs (they are step of movie): two strange error message when option is off.

![screenshot_2017-11-25-07-17-36](https://user-images.githubusercontent.com/24221053/33228096-4cc065ec-d1b3-11e7-86d1-9b7d7f77a72c.png)
