### ISSUE TITLE
When the limit is not in the database

### ISSUE THREAD

**Issue by Raffaele74** [plusCubed/velociraptor#64]
Velociraptor is used when driving.
When driving you cannot look at the device and expects the beep.
When the limits are in maps, there may be stretches without limits.

So, I believe important that Velociraptor:

> It makes it easier to understand that the limit is not there (with a sound - or - not showing the marker limit - or - showing marker filled red)

> Allows a default limit in case of absence. Better default limits (more then one): as you drive near effective limit, it will be active only that one. Example: septum 50, 90, 130 and Velociraptor sounds if they overcome one.
Default must selected by users (responsability)

> I will like if I will can select "beep or speech synthesis"

>What do you think about a specific log-file recording (with gps - speed if it is possible) start stop default-limits to upload OpenStreetMap (manually) when we go home?

**Comment by plusCubed** [comment]
See #48, which covers some of your suggestions.
