### ISSUE TITLE
Help for Here We Go code and id

### ISSUE THREAD

**Issue by Raffaele74** [plusCubed/velociraptor#65]
What is code and id? Here app are two: Here We Go, Here Map Creator.

![screenshot_2017-04-03-21-13-11](https://cloud.githubusercontent.com/assets/24221053/24643047/8aede5e4-190b-11e7-9fce-40d466ef74d3.png)

**Comment by plusCubed** [comment]
They are filled automatically after signing up and viewing the codes in the web page.

**Comment by Raffaele74** [comment]
I've a lot of problems.
I've an Here account, but this page is different.
Error message is very strange.
Can you show me link?
So I can try from pc.

![screenshot_2017-04-04-13-12-10](https://cloud.githubusercontent.com/assets/24221053/24654814/ac94f72a-193b-11e7-9b94-9bde70c08242.png)

**Comment by plusCubed** [comment]
I do not see what is wrong. You have to register for an account and input the correct information (as the error says you need a valid phone number).

**Comment by Raffaele74** [comment]
I insert my number +393357510202 (12-13 number) and 3357510202 and it says invalid.

**Comment by plusCubed** [comment]
So here's the link if you want to try on a computer: https://developer.here.com/plans?create=Public_Free_Plan_Monthly&keepState=true&step=account

**Comment by Raffaele74** [comment]
Thankyou. I did.
Here want a blank: +39 3357510202. Difficult to view on Android device.
Later I put "Company=Personal"
Here said "90 days trial"
I change a translation and add clarification in transaltion that explane when Here finished.

**Comment by plusCubed** [comment]
The plan that the Velociraptor page directs you to has the Basic plan, which is free forever, not the 90 day trial (which is only a button at the top of the page). The tip about the blank might be a good idea to include in the Italian translation.

**Comment by aandea** [comment]
If I use Here maps on computer, from the account page, do I need to copy the AppID for JavaScript/Rest or for Android SDK? 
Is there a way to tell that the AppID and key are good?

**Comment by plusCubed** [comment]
It is the App ID for Javascript/REST. There is no current way to tell that they are correct - I'll add this in the next version.
