### ISSUE TITLE
Bug on setting log for neerds

### ISSUE THREAD

**Issue by Raffaele74** [plusCubed/velociraptor#67]
**Solution 1**  You can enable a larger scroll when log is on.
**Solution 2**  You can put "Avanzate" up (the first) in setting menu.

![img_20170404_100148](https://cloud.githubusercontent.com/assets/24221053/24648720/d7cd3a22-1924-11e7-836d-c057576fb58c.png)

**Comment by plusCubed** [comment]
It is already selectable, the overlay doesn't capture touch.
