### ISSUE TITLE
Development "when I'm slow down"

### ISSUE THREAD

**Issue by Raffaele74** [plusCubed/velociraptor#69]
A beep (different) when I'm slow down.  Because app says me that I'm ok again, or I falling asleep. 

Italy Motorway and Rome-ring. I have an upper limit, but also a lower limit. I should like a beep over xx km/h and under yy km/h.

http://www.autoblog.it/post/828217/limite-minimo-velocita-codice-della-strada-sanzioni

How to tell to OpenStreetMap?

**Comment by plusCubed** [comment]
This is not essential to the app right now, which deals with the problem most people have of the upper speed limit, not the lower.
