### ISSUE TITLE
Additional styling for the speed counter

### ISSUE THREAD

**Issue by spicypixel-** [plusCubed/velociraptor#7]
It might be beneficial to have an option where instead of percentage colour bar change on the realtime speed reading, have a solid ring colour that changes.

Possibly go from blue through to green up to speed limit and switch to red when you go above it, or any variation of this theme. 

Basically anything to reduce the required time to glance at it and get the information needed.

**Comment by techguyone** [comment]
Can I also add, to make an option in settings to remove the 'mph' or 'kph' text from the speed reading, I'd prefer to have the text like in the upper screen, centred. I know what I'm using (mph or kph) as I've already specified that in the settings. I don't need it to constantly display, alternatively if it must be shown, could it be slightly below and outside the speed circle. Then it's not making it harder than needed to read the speed in the circle.

**Comment by hoevenpe** [comment]
Circle does not add any information here, less is more...

Because Google Maps does not show the current speed itself this number is very useful and should be much bigger in my opinion.

**Comment by plusCubed** [comment]
I have made the speedometer use a gradient, and it fills up to the percentage of the speed limit (i.e. when the gauge is full you have hit the speed limit and tolerance). @techguyone I have moved your suggestion to #27
