### ISSUE TITLE
No limits shown

### ISSUE THREAD

**Issue by Boban1108** [plusCubed/velociraptor#71]
The speed is shown perfect, but not speed limits. Only -- . I think I do something wrong. But what?

**Comment by maciejs** [comment]
Same, is it currently working at all?

**Comment by plusCubed** [comment]
You can try adding the HERE Maps database (see the in app option). It's a bit convoluted - sorry about that.

Check the coverage for both OpenStreetMap (the default) and HERE Maps to see if there are speed limits posted around your area - there are links inside the app.

**Comment by Boban1108** [comment]
I registered myself by Heremaps. It was difficault, but I did it. But it takes still about one hour time before it starts to work. Pacient! Now it works. Thanks!

**Comment by plusCubed** [comment]
Glad to hear it works! Do you have any suggestions on how I can make the process clearer/easier?

**Comment by maciejs** [comment]
Boban1108, does route that you drove have speed limits mapped on OpenStreetMap? Mine does, but I did not see speed limits on Friday. However, next day I saw some. Looks like it was a temporary flaw.

**Comment by Boban1108** [comment]
Here Maps registration: on the mobiel phone it is for me a little bit difficault to choice what program and fulfill the form. But I did it correct and it works.

@maciejs : Open Street Map the routes are mostly NOT covered. So the limits I receive from Here Maps. On Fridya I was not on the road.

**Comment by plusCubed** [comment]
Please see my comment on #74 regarding HERE Maps
