### ISSUE TITLE
Can't configure Here Maps coverage

### ISSUE THREAD

**Issue by szyblaszczyk** [plusCubed/velociraptor#72]
Hi. Your app would be very useful but only with Here speed coverage which is great in Here Maps.

How can I configure it? I copied App ID and App Code from JavaScript/REST but it doesn't work. I have: "HereMaps: false".

Thanks!

**Comment by plusCubed** [comment]
Hi, you can try clearing the app data - that'll reset any cached data from OpenStreetMap and use HERE (you'll have to set it up again though)

**Comment by szyblaszczyk** [comment]
Thanks. I did it but Here Maps it's still status "false". Shouldn't be like that, am I right?

**Comment by plusCubed** [comment]
Please see my comment on #74.
