### ISSUE TITLE
feature request: Option to hide limit / Speedometer arc

### ISSUE THREAD

**Issue by g0wfv** [plusCubed/velociraptor#73]
Sounds counter intuitive, right? Why down load a speed limit app to hide the limit?

Well this app is the perfect speedometer add-on! However i'd rather have an option to not have the speed limit displayed until I'm exceeding it.

The second part of the request is the arc around the outside of the speedometer.  Current behaviour seems to as a percentage of a fixed value.  Can this be changed to a percentage of the current limit? Perhaps reverting to a max of limit + a percentage with a different colour if exceeding the limit?

**Comment by plusCubed** [comment]
Added the option in 1.6.0, rolling out now.

The arc's speedometer is to mimic a car's speedometer. The arc used to be a percentage of the speed limit, but when there's no speed limit data, it becomes ambiguous as to what it should be, so I changed it.

Let me know if you have any other suggestions!
