### ISSUE TITLE
Here Sign In not working

### ISSUE THREAD

**Issue by DeckardCain2014** [plusCubed/velociraptor#74]
Currently, the Here Sign In is not working. Only a SignIn-Button is shown, but no edit fields for Username / PW...

**Comment by KevQuoi** [comment]
I have the same issue, no accessible URL so cannot access sign in page.

**Comment by wizonesolutions** [comment]
Having the same issue. And the app doesn't seem to like me putting in my credentials manually either, so I'm kind of stuck and limited to OSM.

**Comment by mixei4** [comment]
Same thing. Any solutions?

**Comment by cfranze** [comment]
Same issue here. Manually adding doesn't seem to work. When I first installed, on Sept. 8, 2017, I used the in app browser to set up my HERE Developer account and the credentials were pulled automatically as they should have been but map or speed data was never pulled from HERE. HERE Maps always reported false in debug. Tried the other solutions to solve that problem which led me to this one. Where I can't log back in to automatically import HERE credentials.

**Comment by unclejohn56** [comment]
HERE API worked for the first few days then stopped.
See: https://drive.google.com/file/d/0B6iFQVfZkKf0Y0lPbXV0MlZXNlE/view 
Cache not playing well perhaps?
I'm attempting to create an earlier version of the App, before the cache was implemented, to test this theory. But learning/sorting problem for Android Studio is going to take a while....

**Comment by plusCubed** [comment]
After investigating I believe HERE has closed their free speed limit API. I'll be removing the feature from the next version. I'm on the lookout for other services, but all of them charge exorbitantly high prices (Google, TomTom, Sygic, HERE, etc.) that I can't afford as a student. If you have any ideas please let me know.

**Comment by unclejohn56** [comment]
Thanks for your advice Daniel. I know what you mean by exorbitantly high prices. Google charge $2,000 per annum. 
I'm going to try another route and lobby our local Government to set up and fund a government server. Would they be able to use OpenStreetMaps code?

**Comment by plusCubed** [comment]
@unclejohn56 OpenStreetMap has a backend that anyone can deploy called Overpass http://overpass-api.de/. It's what I use to run Velociraptor's OSM server.

**Comment by unclejohn56** [comment]
Overpass seems to be stuck on "pending": https://drive.google.com/file/d/0B6iFQVfZkKf0bXk1aERCOEpNX0E/view?usp=sharing

**Comment by plusCubed** [comment]
@unclejohn56 Only one of them needs to be "true" to work (usually that'll be velociraptor-server, the one I deployed for the app). If there are no speed limits, that means OSM doesn't have your location, but do double check using the coverage map link in the app.

**Comment by unclejohn56** [comment]
Daniel, Thanks for the explanation. It explains why this App has continued to work for me all the time :-)
I walked out onto the street and this is the results:
https://drive.google.com/file/d/0B6iFQVfZkKf0Tno1aTZiRVdhZ00/view?usp=sharing
Must have cuptured all this data in the first couple of days operation so many weeks ago.
For areas not covered I use this app with manual settings:
https://play.google.com/store/apps/details?id=com.sqzsoft.speedalarm
It works great but I think that a button for each speed limit setting is a bit of overkill as speed limits here vary in 10 kmph steps so a simple jab of a + or - key would be sufficient.
I reckon if you could combine manual override features into your App you would be onto a real winner. Particularly if these were captured in the cache.

**Comment by unclejohn56** [comment]
@plusCubed I've noticed that the Speed Limit is sometimes enclosed in brackets, eg. (60). What is the meaning of the brackets?

**Comment by unclejohn56** [comment]
@plusCubed I was thinking and researching how one might cache manually entered speed limit data when I came accross this App/Project:
https://github.com/nguillaumin/osmtracker-android
https://play.google.com/store/apps/details?id=me.guillaumin.android.osmtracker&hl=en
It would seem to me that it would not be too difficult to merge relavant sections of this code into Velociraptor. It seems that this code would also provide a good stepping stone for the next step. Uploading speed limit data to OSM.
I appreciate that your study commitments prevent you putting the required hours into such a big change.
However I would appreciate some feedback on whether you think this enhancement is feasable and whether incorporating OSMTracker is a good idea?

**Comment by plusCubed** [comment]
1.6.0 introduces subscription plans for HERE and TomTom (provided through Sygic's APIs). It's currently rolling out.

@unclejohn56 I have looked into it, but their codebase is radically different. I currently do not have the time to do so (I'm a full-time high school student), sorry about that!

**Comment by Robroi2000** [comment]
**@unclejohn56** The speed limit enclosed in brackets means that there was no information found (e.g. no street was found, runtime exception) for the current location, so the last found speed limit is displayed enclosed in brackets.

**Comment by unclejohn56** [comment]
Thanks for the explanation.
