### ISSUE TITLE
Android auto

### ISSUE THREAD

**Issue by ponente67** [plusCubed/velociraptor#75]
Nelle impostazioni della app, per l'integrazione con android auto viene richiesto di scaricare velociraptor sa da apkmirror. L'ho fatto ed ho scaricato la mappa più recente.
Non mi è chiaro cosa devo fare a questo punto per vedere le funzionalità sulla mappa di Google mappa in android auto.
Grazie e complimenti

**Comment by plusCubed** [comment]
https://www.apkmirror.com/apk/daniel-ciao/velociraptor-full/

Let me know if you have any questions!
