### ISSUE TITLE
HERE Maps reports "false" in debug

### ISSUE THREAD

**Issue by unclejohn56** [plusCubed/velociraptor#76]
HERE API worked for the first few days then stopped.
See: https://drive.google.com/file/d/0B6iFQVfZkKf0Y0lPbXV0MlZXNlE/view
Cache not playing well perhaps?
I'm attempting to create an earlier version of the App, before the cache was implemented, to test this theory. But learning/sorting install problems for Android Studio is going to take a while....

**Comment by plusCubed** [comment]
Please see my comment on #74
