### ISSUE TITLE
[Issue] v1.6.0 speed alert BELOW speed limit

### ISSUE THREAD

**Issue by cawilliamson** [plusCubed/velociraptor#79]
Hi there!

Firstly - absolutely AWESOME job on v1.6.0 - subscribed to both sources straight away! TOP WORK!!

Secondly - I have found one issue - I am getting the speeding audible alert (and the current speed is turning red) whilst within the speed limit. By this - I meaning Velociraptor shows the speed limit as 30mph but alerts at 20mph so the data is spot on - just the alert triggers too low. I have checked the speeding tolerance and it's set as 0mph PLUS 0% so shouldn't be alerting early.

I'm a beta tester so happy to test a beta build if that helps!

Thanks!

**Comment by davidnnc** [comment]
I second this comment. Great app, but having the same issue about alerting to an overspeed condition when the actual speed is anywhere from 5 to 30 MPH below the speed limit.

**Comment by cawilliamson** [comment]
This one is fixed in the latest beta version, thanks!
