### ISSUE TITLE
[Question] v1.6.0 subscription options

### ISSUE THREAD

**Issue by cawilliamson** [plusCubed/velociraptor#80]
Hi there!

I've subscribed to HERE Maps and TomTom in your app but I'm curious about a few things:

- Which one gets priority if they're both subscribed to? (i.e. if TomTom says 40 and HERE says 30 as the limit - which do you use?)
- Is there any benefit to subscribing to more than one?
- Is there any way to disable OpenStreetMap data? (or do the subscription options get priority anyway?)

Thanks a lot in advance - I really appreciate your work on this app - makes Google Maps AWESOME!! :+1: 

P.S. I would happily pay for speed camera alerts too (new driver so whilst I don't intentionally speed - knowing where to be extra careful would be amazing!) :+1:

**Comment by plusCubed** [comment]
- HERE > TomTom > OSM
- If HERE doesn't have the speed limit, it'll defer to TomTom
- Subscription options get priority

Let me know if you have any other questions! :) Thanks
