### ISSUE TITLE
Accessibility Settings

### ISSUE THREAD

**Issue by DanielWent** [plusCubed/velociraptor#81]
Hello. I love using the velociraptor app and am considering getting a TomTom subscription for speed limits. However, I am wondering if you been affected by the recent Google crack down on Apps using Accessibility Settings and, if so, if there any sign of a work around to maintain the existing functionality? Thanks!

**Comment by plusCubed** [comment]
Hi, as you may have read, they've delayed the stricter rules, so it's good for now. I'll be maintaining this app for the foreseeable future, and if Google doesn't allow it on the store I'll distribute it here.
