### ISSUE TITLE
File google-services.json is missing. The Google Services Plugin cannot function without it. 

### ISSUE THREAD

**Issue by SaadNadeem123** [plusCubed/velociraptor#88]
The google-services.json file is missing from the project. While gradle building, it cant find the file. I searched manually but there was no file. How can i include this file or where do i need to register on console to get the file? I included my project on google firebase console and downloaded the json file but its still not picking it up. As you can see from the image that i copied the file in app but it still isnt working.

![screenshot 1](https://user-images.githubusercontent.com/33824953/36376486-1bf30466-1528-11e8-8199-4017d4d0d481.png)

**Comment by plusCubed** [comment]
I have it at `app/google-services.json`
