### ISSUE TITLE
Overlay not shown in google maps any more

### ISSUE THREAD

**Issue by tY-Software** [plusCubed/velociraptor#89]
Velociraptor is configured to show in google maps, but it doesn't any more.
The speed limit overlay is only showing up in the veloricaptor settings.

**Comment by plusCubed** [comment]
In Velociraptor settings, are all 3 permissions granted (on Android 6.0+)?

**Comment by tY-Software** [comment]
Damn... The accessibility service must have been disabled by some update or something.

Thanks for the support and this great app!
